### ISSUE TITLE
ECIP-1099 verification of solutions using open-ethereum-pool

### ISSUE THREAD

**Issue by Konstantin35** [eth-classic/ethash#1]
Dear developers, you are planning to finish ethash.go after all it is used for pools open-ethereum-pool
currently, mining is not possible.

- core-geth --mordor
- open-ethereum-pool
- nanominer

[img](https://user-images.githubusercontent.com/28952414/97882955-4bf8c980-1d35-11eb-8a6e-6f4305e7911f.png)

**Comment by iquidus** [comment]
work is in progress on this, you can follow it here: https://github.com/etclabscore/etchash

**Comment by Konstantin35** [comment]
Gracias
